### PR TITLE
Hip joint limit

### PR DESCRIPTION
**Pull request by mebbaid**
This PR adjust the hip roll limits for `ergoCubGazeboV1` as well as make the limit congruent with the one reported for the real robot in https://github.com/ami-iit/robots-configuration/blob/devel_ergoCubSN000/ergoCubSN000/hardware/mechanicals/left_leg-eb8-j0_3-mec.xml

### CODE REVIEW

**Comment by mebbaid** [comment]
@lrapetti , this was opened in place of #1 , and more in line with the recommendation of icub-tech. Give it a look, and let me know.

**Review by lrapetti — COMMENTED** [review]
Hi @mebbaid, I noticed in this PR you added also some commits that are not relate to this PR (I think that are due to the fact that the `ami-iit/master` is not aligned with `icub-tech/master`. In order to avoid having different commit history, I am wondering why you don't open this PR directly towards `icub-tech/master` instead of using `ami-iit` fork?

**Comment by lrapetti** [comment]
We can close this, @mebbaid will open the PR directly upstream

**Comment by mebbaid** [comment]
As per the suggestion, this limit change together with modified PID values will be merged directly upstream

**Pull request closed without merging**
