### PR TITLE
adjusting the hip joints limits

### PR DESCRIPTION
**Pull request by mebbaid**
Adjust the left and right `hip_roll` limits.

### CODE REVIEW

**Comment by mebbaid** [comment]
@lrapetti this was used to help solving the issue in this comment https://github.com/ami-iit/element_walking-with-payload/issues/44#issuecomment-1432812146

**Comment by lrapetti** [comment]
I think those limits should be changed at the model generation level 
@pattacini

**Comment by pattacini** [comment]
Checking with @nicogene what we need to do with this.

**Comment by Nicogene** [comment]
Hi @mebbaid!

I advise to change the limits here:

https://github.com/ami-iit/ergocub-software/blob/ef9652e334c665b44987ff292c1bed6ce5ec16f3/urdf/simmechanics/data/ergocub/ERGOCUB_joint_all_parameters.csv#L12

https://github.com/ami-iit/ergocub-software/blob/ef9652e334c665b44987ff292c1bed6ce5ec16f3/urdf/simmechanics/data/ergocub/ERGOCUB_joint_all_parameters.csv#L18

Otherwise, the next generation will overwrite your changes.

Moreover, if those are the correct limits I advise opening the PR upstream, thanks!

**Comment by mebbaid** [comment]
Grazi @Nicogene , I will follow your advice. Closing this PR

**Pull request closed without merging**
